### ISSUE TITLE
android.widget.FrameLayout$LayoutParams cannot be cast to android.support.design.widget.CoordinatorLayout$LayoutParams

### ISSUE THREAD

**Issue by kouhengsheng** [natario1/BottomSheetCoordinatorLayout#8]
java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.support.design.widget.CoordinatorLayout$LayoutParams
        at com.otaliastudios.bottomsheetcoordinatorlayout.BottomSheetCoordinatorBehavior.from(BottomSheetCoordinatorBehavior.java:37)
        at com.otaliastudios.bottomsheetcoordinatorlayout.BottomSheetCoordinatorLayout.onMeasure(BottomSheetCoordinatorLayout.java:87)

**Comment by bloooi** [comment]
I think this project has not update any more.
